apiVersion: v1
kind: Service
metadata:
  name: ptt-signalling
spec:
  selector:
    app: ptt-signalling
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 18102
    name: grpc
    targetPort: 18102
  - protocol: "TCP"
    port: 9443
    name: signalling
    targetPort: 9443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptt-signalling
spec:
  selector:
    matchLabels:
      app: ptt-signalling
  replicas: 1
  template:
    metadata:
      labels:
        app: ptt-signalling
    spec:
      containers:
      - env:
        - name: GST_SERVER_HOST
          value: ptt-server
        - name: SIGNALLING_CLIENT_HOST
          value: ptt-signalling
        image: "push2talk_signalling:1.0"
        imagePullPolicy: IfNotPresent
        name: ptt-signalling
        ports:
        - containerPort: 18102
          name: grpc
          protocol: TCP
        - containerPort: 9443
          hostPort: 9443
          name: signalling
          protocol: TCP  