apiVersion: v1
kind: Service
metadata:
  name: ptt-server
spec:
  selector:
    app: ptt-server
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 18101
    targetPort: 18101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptt-server
spec:
  selector:
    matchLabels:
      app: ptt-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ptt-server
    spec:
      containers:
      - env:
        - name: GST_DEBUG
          value: 3,push2talk_gst:4
        image: "push2talk_server:1.0"
        imagePullPolicy: IfNotPresent
        name: ptt-server
        ports:
        - containerPort: 18101
          hostPort: 18101
          protocol: TCP
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true